import {
  changeGoodsStatus,
  isOrNot,
  bland
} from '../optionConfig/index'
export default {
  queryUrl: '',
  visibleCtr: true,
  queryFields: {
    labelWidth: '130px',
    fields: [ {
      name: '货主',
      key: 'num',
      editor: 'select',
      clearable: true,
      filterable: true,
      config: changeGoodsStatus
    }, {
      name: 'SKU编码',
      key: 'num',
      editor: 'input'
    }, {
      name: '商品名称',
      key: 'num',
      editor: 'input'
    }, {
      name: '商品标签',
      key: 'num',
      editor: 'select',
      clearable: true,
      config: changeGoodsStatus
    }, {
      name: '品牌',
      key: 'num',
      editor: 'select',
      clearable: true,
      filterable: true,
      config: bland
    }, {
      name: '是否有可售库存',
      key: 'num',
      editor: 'select',
      clearable: true,
      filterable: true,
      config: isOrNot
    }, {
      name: '库存是否缺货',
      key: 'num',
      editor: 'select',
      clearable: true,
      filterable: true,
      config: isOrNot
    }, {
      name: '安全库存预警',
      key: 'num',
      editor: 'select',
      clearable: true,
      filterable: true,
      config: changeGoodsStatus
    }, {
      name: '库存状态',
      key: 'num',
      editor: 'select',
      clearable: true,
      filterable: true,
      config: changeGoodsStatus
    } ]
  },
  page: true,
  fieldWidth: '200px',
  record: {
    fields: [ {
      name: '货主',
      key: 'num'
    }, {
      name: '所属仓库',
      key: 'num'
    }, {
      name: 'SKU编码',
      key: 'skuNum',
      style: {
        color: 'blue',
        cursor: 'pointer'
      }
    }, {
      name: '商品标签',
      key: 'num'
    }, {
      name: '商品名称',
      key: 'num'
    }, {
      name: '规格',
      key: 'num'
    }, {
      name: '品牌',
      key: 'num'
    }, {
      name: '单位',
      key: 'num'
    }, {
      name: '实际库存',
      key: 'num',
      type: 'date'
    }, {
      name: '可售库存',
      key: 'num'
    }, {
      name: '预留锁定库存',
      key: 'num'
    }, {
      name: '下推锁定库存',
      key: 'num'
    }, {
      name: '缺货库存',
      key: 'num'
    }, {
      name: '在途库存',
      key: 'num',
      type: 'date'
    }, {
      name: '安全库存',
      key: 'num'
    }, {
      name: '库存状态',
      key: 'num',
      type: 'date'
    } ]
  }
}
